export const SET_SETTINGS           = "SET SETTINGS";
export const SET_DEFAULT_SETTINGS   = "SET DEFAULT SETTINGS";
export const SET_INITIAL_SETTINGS   = "SET INITIAL SETTINGS";
export const RESET_DEFAULT_SETTINGS = "RESET DEFAULT SETTINGS";

export const NAVBAR_GET_ITEMS   = "GET NAVBAR ITEMS";
export const NAVBAR_SET_ITEMS   = "SET NAVBAR ITEMS";
export const NAVBAR_RESET_ITEMS = "RESET NAVBAR ITEMS";
export const NAVBAR_MOUSE_ENTER    = "NAVBAR MOUSE ENTER";
export const NAVBAR_MOUSE_LEAVE    = "NAVBAR MOUSE LEAVE";

export const ENQUEUE_SNACKBAR = "ENQUEUE_SNACKBAR";
export const CLOSE_SNACKBAR   = "CLOSE_SNACKBAR";
export const REMOVE_SNACKBAR  = "REMOVE_SNACKBAR";

export const OPEN_BACKDROP = "OPEN_BACKDROP";
export const CLOSE_BACKDROP = "CLOSE_BACKDROP";