export const COMPANY_GET_PAGE         = "COMPANY_GET_PAGE";
export const COMPANY_GET_PAGE_SUCCESS = "COMPANY_GET_PAGE_SUCCESS";

export const COMPANY_GET         = "COMPANY_GET";
export const COMPANY_GET_SUCCESS = "COMPANY_GET_SUCCESS";

export const COMPANY_SAVE          = "COMPANY_SAVE";
export const COMPANY_SAVE_SUCCESS = "COMPANY_SAVE_SUCCESS";

export const COMPANY_OPEN_FORM  = "COMPANY_OPEM_FORM";
export const COMPANY_CLOSE_FORM = "COMPANY_CLOSE_FORM";
export const COMPANY_CLEAR_FORM = "COMPANY_CLEAR_FORM";


